name: get_flutter_version
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.8.0
  http: ^1.3.0
  intl: ^0.20.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
